<?php

/**
 * @file
 * Primary module hooks for JS Example module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function js_example_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_js_test_form' || $form_id === 'node_js_test_edit_form') {
    $form['#attached']['library'][] = 'js_example/js-phone';
    return $form;
  }
}
