<?php

use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 * This is used to call the custom function when hit the submit button on the
 * login form.
 */
function plugin_example_form_user_login_form_alter(&$form, $form_state, $form_id) {
	$form['#submit'][] = 'customRedirectUrl';
}

/**
 * This is used to change the route to the desired page when hit the submit button.
 */
function customRedirectUrl($form, $form_state) {
	$url = Url::fromRoute('plugin_example.example');
	$form_state->setRedirectUrl($url);
}

?>